package com.linagora.openpaas.gatling.core

object LoginTemplateRequestsList {
  val loadTemplate = Array(
    "/",
    "/login?continue=%2F",
    "/components/lodash/dist/lodash.min.js",
    "/components/mdi/css/materialdesignicons.min.css",
    "/components/animate.css/animate.css",
    "/components/bootstrap/dist/js/bootstrap.min.js",
    "/components/roboto-fontface/css/roboto-fontface.css",
    "/components/jquery/dist/jquery.min.js",
    "/components/angular-route/angular-route.min.js",
    "/components/restangular/dist/restangular.min.js",
    "/components/angular-moment/angular-moment.min.js",
    "/components/remarkable-bootstrap-notify/bootstrap-notify.min.js",
    "/components/angular-sanitize/angular-sanitize.min.js",
    "/components/moment/min/moment.min.js",
    "/components/angular-strap/dist/angular-strap.tpl.min.js",
    "/components/angular-component/dist/angular-component.min.js",
    "/components/angular/angular.min.js",
    "/components/angular-strap/dist/angular-strap.min.js",
    "/components/angular-messages/angular-messages.min.js",
    "/components/angular-cookies/angular-cookies.min.js",
    "/js/material.js",
    "/components/angular-feature-flags/dist/featureFlags.js",
    "/components/material-admin/js/modules/form.js",
    "/components/dynamic-directive/dist/dynamic-directive.min.js",
    "/components/waves/dist/waves.min.js",
    "/js/welcome/app.js",
    "/js/welcome/app.run.js",
    "/js/constants.js",
    "/components/angular-translate/angular-translate.min.js",
    "/generated/js/welcome/js/core",
    "/moment-timezone/builds/moment-timezone-with-data.min.js",
    "/generated/css/welcome/styles.css",
    "/images/logo-tiny.png",
    "/images/white-logo.svg",
    "/views/welcome/partials/home",
    "/components/roboto-fontface/fonts/Roboto-Medium.woff2",
    "/components/roboto-fontface/fonts/Roboto-Regular.woff2",
    "/components/roboto-fontface/fonts/Roboto-RegularItalic.woff2",
    "/components/mdi/fonts/materialdesignicons-webfont.woff2?v=2.0.46",
    "/api/i18n",
    "/images/login-1920.jpg"
  );
}
